--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/26/2021 8:33:58 PM
-- Server version: 5.5.5-10.4.21-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO llamacielo.usuarios(usuario_id, usuario_tipo, usuario_nombre, usuario_dni, usuario_password, usuario_fechaInicio, usuario_activo, usuario_email) VALUES
(1, 2, 'usuario prueba 1', 14987776, '14987776', '2021-09-14', 1, 'usuario1@gmail.com');
INSERT INTO llamacielo.usuarios(usuario_id, usuario_tipo, usuario_nombre, usuario_dni, usuario_password, usuario_fechaInicio, usuario_activo, usuario_email) VALUES
(2, 2, 'usuario prueba 2', 16445344, '16445344', '2021-09-09', 1, 'usuario2@hotmail.com');
INSERT INTO llamacielo.usuarios(usuario_id, usuario_tipo, usuario_nombre, usuario_dni, usuario_password, usuario_fechaInicio, usuario_activo, usuario_email) VALUES
(3, 2, 'usuario prueba 3', 20789654, '20789654', '2021-08-10', 1, 'usuario3@yahoo.com');
INSERT INTO llamacielo.usuarios(usuario_id, usuario_tipo, usuario_nombre, usuario_dni, usuario_password, usuario_fechaInicio, usuario_activo, usuario_email) VALUES
(4, 2, 'usuario prueba 4', 96785434, '96785434', '2021-08-19', 1, 'usuario4@outlook.com');